apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::247018008061:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-xNOfbZRm8TEO
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-pod-reader
      userarn: arn:aws:iam::247018008061:user/harish
      username: harish

kind: ConfigMap
metadata:
  creationTimestamp: "2026-02-19T06:25:05Z"
  name: aws-auth
  namespace: kube-system
  uid: 6ff1599f-1244-4341-930c-b524ae56f426  #don't change this uid
